### ISSUE TITLE
Formal releases

### ISSUE THREAD

**Issue by johnmccabe** [blackducksoftware/hub-client-go#45]
Hi,
Are there any plans to return to formal releases of this package so as to avoid having to pin `go mod` to commits, the last release was almost a year and a half ago.
/John

**Comment by tandr** [comment]
@johnmccabe John, I am not the owner of the library, but...
It is good (and also scary a bit too) to see someone is using this library - we (not the original blackduck team) kind of assumed it was long forgotten...
This library was on the far side of the woods for quite a bit of time. But since we needed something to start with, we have picked it up for an internal project, and discovering cobwebs and gotchas as we go. As you can see from commit log, we are actively working it. There are at least couple of more changes on a pipeline, which should make it a bit more predictable when working with latest servers (all hail an Accept header).

If we tag this library today with something like 0.0.1, would it be helpful?

**Comment by johnmccabe** [comment]
Hi @tandr a tag is not critical at this point, I just wanted to find out what was happening. When you are ready to tag I'd continue from the previous tag version 0.9.4 (I believe), as if you revert back to an earlier semver release it'll cause more problems.

**Comment by tandr** [comment]
tagged v0.9.5

I am not 100% sure when and how often we are going to tag this next time, but at least this one is out :)
